sonar.projectKey=devops-ai-course
sonar.projectName=DevOps AI Course

sonar.sources=devops-frontend/src
sonar.tests=devops-frontend/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**

sonar.typescript.lcov.reportPaths=devops-frontend/coverage/lcov.info

sonar.host.url=https://sonar.codevialab.com
